[build]
command = """
curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash && \
cargo-binstall typst-cli ripgrep && \
\
curl -OL https://www.7-zip.org/a/7z2409-linux-x64.tar.xz && \
tar -xvf 7z2409-linux-x64.tar.xz 7zz && ln -s 7zz 7z && \
export PATH=$PATH:$(pwd) && \
\
bash scripts/download_fonts.sh && \
\
pnpm install && \
pnpm build
"""
# `cargo binstall` not works here
