name: Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - uses: typst-community/setup-typst@v4
      - name: Restore cached fonts
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            fonts/
          key: fonts-${{ hashFiles('scripts/download_fonts.sh') }}
          restore-keys: |
            fonts-${{ hashFiles('scripts/download_fonts.sh') }}
            fonts-
      - uses: taiki-e/install-action@v2
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          tool: ripgrep
      - name: Install fonts
        shell: bash
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          bash scripts/download_fonts.sh
      - run: pnpm install
      - run: pnpm build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: "./dist"
  check-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - uses: typst-community/setup-typst@v4
      - run: |
          pnpm check-issues >> "$GITHUB_STEP_SUMMARY"
        env:
          GH_TOKEN: ${{ github.token }}

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: fd-find,typstyle@0.13.11  # typstyle shipped with tinymist v0.13.14
      - name: Run typstyle
        run: |
          typstyle --check --line-width 120 $(fd --extension typ --exclude 'html-bindings*.typ')
