name: Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: typst-community/setup-typst@v4
      - run: mkdir -p dist
      - run: typst compile index.typ --features html dist/index.html
