name: Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: just
      - uses: typst-community/setup-typst@v4
      - run: just compile
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: "./dist"
